// examples/example-solidjs/src/App.tsx
import { ErrorBoundary } from "solid-js";
import { I18nProvider, Trans } from "./locales";
import Counter from "./components/Counter";
import LanguageSwitcher from "./components/LanguageSwitcher";
import TextView from "./components/TextView";
import solidLogo from "./assets/solid.svg";
import viteLogo from "/vite.svg";
import "./App.css";

function App() {
  return (
    <I18nProvider>
      <ErrorBoundary fallback={err => <div>Error: {err.message}</div>}>
        <LanguageSwitcher />
        <div>
          <a href="https://vite.dev" target="_blank">
            <img src={viteLogo} class="logo" alt="Vite logo" />
          </a>
          <a href="https://solidjs.com" target="_blank">
            <img src={solidLogo} class="logo solid" alt="Solid logo" />
          </a>
        </div>
        <h1>Vite + Solid</h1>
        <div class="card">
          <Counter />
          <TextView />
          <p>
            Edit <code>src/App.tsx</code> and save to test HMR
          </p>
        </div>
        <p class="read-the-docs">
          Click on the Vite and Solid logos to learn more
        </p>
        <Trans component="h2">欢迎使用Solid</Trans>
      </ErrorBoundary>
    </I18nProvider>
  );
}

export default App;

// examples/example-qwik/src/app.tsx
import { component$ } from "@builder.io/qwik";

import { I18nProvider, Trans } from "./locales";
import LanguageSwitcher from "./components/LanguageSwitcher";
import Counter from "./components/Counter";
import TextView from "./components/TextView";
import qwikLogo from "./assets/qwik.svg";
import viteLogo from "/vite.svg";
import "./app.css";

export const App = component$(() => {
  return (
    <I18nProvider>
      <div>
        <LanguageSwitcher />
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} class="logo" alt="Vite logo" />
        </a>
        <a href="https://qwik.dev" target="_blank">
          <img src={qwikLogo} class="logo qwik" alt="Qwik logo" />
        </a>
      </div>
      <h1>Vite + Qwik</h1>
      <div class="card">
        <Counter />
      </div>
      <TextView />
      <Trans component="h2" msg="欢迎使用Solid" />
      <p class="read-the-docs">
        Click on the Vite and Qwik logos to learn more
      </p>
    </I18nProvider>
  );
});
