// examples/example-cra/src/components/LanguageSwitcher.tsx
import {
  type SupportLocale,
  locale,
  changeLanguage,
  languageList,
  useTranslation
} from "@/locales";
import { type ChangeEvent } from "react";

function LanguageSwitcher() {
  const { i18n } = useTranslation();
  const onChange = (event: ChangeEvent<HTMLSelectElement>) => {
    const locale = event.target.value as SupportLocale;
    changeLanguage(locale);
    i18n.changeLanguage(locale);
  };

  return (
    <select
      value={locale}
      onChange={onChange}
      style={{
        position: "absolute",
        right: 30,
        top: 30,
        padding: 6,
        fontSize: 15
      }}
    >
      {languageList.map(option => (
        <option key={option.value} value={option.value}>
          {option.label}
        </option>
      ))}
    </select>
  );
}

export default LanguageSwitcher;

// examples/example-qwik/src/components/LanguageSwitcher.tsx
import {
  locale,
  changeLanguage,
  languageList,
  type SupportLocale
} from "@/locales";
import {
  component$,
  useSignal,
  $,
  type QRLEventHandlerMulti
} from "@builder.io/qwik";

const LanguageSwitcher = component$(() => {
  const lang = useSignal<SupportLocale>(locale);

  const onChange: QRLEventHandlerMulti<Event, HTMLSelectElement> = $(event => {
    const target = event.target as HTMLSelectElement;
    const localeValue = target.value as SupportLocale;
    lang.value = localeValue;
    changeLanguage(localeValue);
  });

  return (
    <select
      value={lang.value}
      onChange$={onChange}
      style={{
        position: "absolute",
        right: "30px",
        top: "30px",
        padding: "6px",
        "font-size": "15px"
      }}
    >
      {languageList.map(option => (
        <option value={option.value} key={option.value}>
          {option.label}
        </option>
      ))}
    </select>
  );
});

export default LanguageSwitcher;
