// examples/example-solidjs/src/components/LanguageSwitcher.tsx
import {
  locale,
  changeLanguage,
  languageList,
  type SupportLocale
} from "@/locales";
import { createSignal, For, type JSX } from "solid-js";

function LanguageSwitcher() {
  const [value, setValue] = createSignal<SupportLocale>(locale);
  const onChange: JSX.ChangeEventHandlerUnion<
    HTMLSelectElement,
    Event
  > = event => {
    const locale = event.target.value as SupportLocale;
    setValue(locale);
    changeLanguage(locale);
  };

  return (
    <select
      value={value()}
      onChange={onChange}
      style={{
        position: "absolute",
        right: "30px",
        top: "30px",
        padding: "6px",
        "font-size": "15px"
      }}
    >
      <For each={languageList}>
        {option => <option value={option.value}>{option.label}</option>}
      </For>
    </select>
  );
}

export default LanguageSwitcher;

// examples/example-react-i18next/src/components/LanguageSwitcher.tsx
import {
  type SupportLocale,
  locale,
  changeLanguage,
  languageList
} from "@/locales";
import { useState, type ChangeEvent } from "react";

function LanguageSwitcher() {
  const [value, setValue] = useState(locale);
  const onChange = (event: ChangeEvent<HTMLSelectElement>) => {
    const locale = event.target.value as SupportLocale;
    setValue(locale);
    changeLanguage(locale);
  };

  return (
    <select
      value={value}
      onChange={onChange}
      style={{
        position: "absolute",
        right: 30,
        top: 30,
        padding: 6,
        fontSize: 15
      }}
    >
      {languageList.map(option => (
        <option key={option.value} value={option.value}>
          {option.label}
        </option>
      ))}
    </select>
  );
}

export default LanguageSwitcher;
